version: 2.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
  run-component-tests:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
      - run:
          name: Run Cypress component tests
          command: npx cypress run --component
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - start-server
      - run-component-tests
      - deploy-to-render-staging:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
